// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "products service",
    "version": "1"
  },
  "paths": {
    "/products/": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "IProduct": {
      "properties": {
        "description": {
          "title": "IProduct.description",
          "type": "string"
        },
        "id": {
          "title": "IProduct.id",
          "type": "string"
        },
        "price": {
          "title": "IProduct.price",
          "type": "number"
        },
        "title": {
          "title": "IProduct.title",
          "type": "string"
        }
      },
      "required": [
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "IProduct",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/IProduct",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    }
  },
  "securityDefinitions": {}
};